[package]
name = "protocol"
version = "0.1.0"
authors = ["xiaohuo <xiaohuo200@gmail.com>"]

[dependencies]
network = {path ="../network" }
basictype = {path="../basictype"}
serialization = {path="../serialization"}
