[package]
name = "monadmacro"
version = "0.1.0"
authors = ["xiaohuo <xiaohuo200@gmail.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
serialization = { path = "../serialization"}

[lib]
proc-macro = true
